services:
  cbil-frontend:
    image: cbil-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cbil-frontend
    restart: always
    networks:
      - main_network
    env_file:
      - ./frontend/.env
  cbil-backend:
    image: cbil-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cbil-backend
    restart: always
    networks:
      - main_network
    env_file:
      - ./frontend/.env

networks:
  main_network:
    name: main_network
    external: true