services:
  image-processing-frontend:
    image: image-processing-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: image-processing-frontend
    restart: always
    networks:
      - main_network
    env_file:
      - ./frontend/.env
  image-processing-backend:
    image: image-processing-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: image-processing-backend
    restart: always
    networks:
      - main_network
    env_file:
      - ./frontend/.env

networks:
  main_network:
    name: main_network